### ISSUE TITLE
Works in workflow

### ISSUE THREAD

**Issue by hannahfrost** [samvera-labs/hyku#1033]
Currently there is a simple, quick-n-dirty Review and Approve panel at the bottom of a work show page. It works, but it is a weak UX. 

See also https://github.com/projecthydra-labs/hyrax/issues/853 and https://github.com/projecthydra-labs/hyrax/issues/857 which touch on some of the UX requirements.

**Comment by jcoyne** [comment]
That looks really nice. Thanks Gary.

**Comment by hannahfrost** [comment]
Agreed! I really like it @ggeisler

**Comment by mjgiarlo** [comment]
Love it! Thank you, @ggeisler. Should we move to Ready column, @hannahfrost @jcoyne?

**Comment by ggeisler** [comment]
If we want to go with this, I'll note one thing that might not obvious from the mockup: In the Relationships section I would only show the items that have values; in other words, in contrast to the current page, don't show the line "In Generic work: There are no Generic work relationships." I think the user will understand they only see things that have values (already the current behavior for the "Descriptions" metadata fields).

**Comment by hannahfrost** [comment]
@ggeisler Would you like to break this into separate tickets, for the new Work design and for the Work in review design?

**Comment by ggeisler** [comment]
@hannahfrost I created #1215 to serve as the ticket for the updated Works layout. I think this ticket can serve as the ticket for the new way of handling the Workflow/review panel.

To prevent confusion, it might be better to implement #1215 before this one, though, so maybe this ticket needs to moved out of Ready or otherwise noted that it is blocked by #1215?

**Comment by jcoyne** [comment]
Should this still be in the November 2017 milestone? @hannahfrost @mjgiarlo
