### ISSUE TITLE
Updating a photo object does not actually update the photo.

### ISSUE THREAD

**Issue by dbernstein** [samvera-labs/hyku#1182]
### Descriptive summary
I uploaded  35 photos associated with a single object and realized that one of photos needed editing.  So I edited the file locally and added a new version.   Even though the UI appeared to receive the upload and recorded the successful update, the  old version the file unexpectedly remained visible.  

### Steps to reproduce the behavior

1.  Add new image work.
2. Upload a single photo.
3. After successful upload,  navigate to the photo.
4. Click "Edit This File",  click versions tab, select a new file, and click "Upload new version" 
5. Verify that neither the thumbnail nor the downloaded file reflects the change.

Commit: ?
Version: Hyku v1.0.0.beta1

Reference object: http://buddhadharma.pilot.hykudirect.org/collections/83aa88cc-32d2-43ec-9339-76f7d54a0680?locale=en

https://app.honeybadger.io/projects/48327/faults/33736521

**Comment by atz** [comment]
Works for me locally.  The thumbnail generation is asynchronous, so it is not immediate, but after a few seconds, if I refresh the page, the new thumbnail shows.  Download is likewise correct.

My log says:
```
[ActiveJob] [CharacterizeJob] [ea9e25bd-a271-4283-9462-e0f6d9d5d780] Ran characterization on 9p2909328/files/3c46f1c0-f8c4-4717-b06d-f9f504400203 (image/png)
[ActiveJob] [CharacterizeJob] [ea9e25bd-a271-4283-9462-e0f6d9d5d780] Enqueued CreateDerivativesJob (Job ID: f79221c2-8cb5-495e-81ec-3c52687967c1) to Async(default) with arguments: #<GlobalID:0x007f8ab75eb160 @uri=#<URI::GID gid://internal/FileSet/9p2909328>>, "9p2909328/files/3c46f1c0-f8c4-4717-b06d-f9f504400203", "/var/folders/6q/13dm9dcn1qx_gw9x66lhl7jc0000gq/T/RackMultipart20170531-9191-1rw9rgl.png"
[ActiveJob] [CharacterizeJob] [ea9e25bd-a271-4283-9462-e0f6d9d5d780] Performed CharacterizeJob (Job ID: ea9e25bd-a271-4283-9462-e0f6d9d5d780) from Async(default) in 4110.2ms
[ActiveJob] [CreateDerivativesJob] [f79221c2-8cb5-495e-81ec-3c52687967c1] Performing CreateDerivativesJob (Job ID: f79221c2-8cb5-495e-81ec-3c52687967c1) from Async(default) with arguments: #<GlobalID:0x007f8aa2362e58 @uri=#<URI::GID gid://internal/FileSet/9p2909328>>, "9p2909328/files/3c46f1c0-f8c4-4717-b06d-f9f504400203", "/var/folders/6q/13dm9dcn1qx_gw9x66lhl7jc0000gq/T/RackMultipart20170531-9191-1rw9rgl.png"
```

**Comment by atz** [comment]
We have some job chaining (via `perform_later`) happening. In a robust system like our AWS setup, that means the job might well be picked up by a worker on a different box altogether with a separate filesystem.  We have tried to anticipate that, so each class does:
```ruby
filename = Hyrax::WorkingDirectory.find_or_retrieve(file_id, file_set.id, filepath)
```
I have no idea why it is useful to have that method then, in its first line, check its 3rd and optional parameter and do:
```ruby
return filepath if filepath && File.exist?(filepath)
```

... but it does.  If I wanted to give you 3 arguments just to tell me `File.exist?(third_arg)`, I would have done that myself.  @eefahy the job workers share some aspect of the filesystem (in this case `/tmp`) to make this feasible?  That seems odd. 

In any case, those jobs have anticipated the problem of finding the file on the local filesystem.  `IngestFileJob`, the one throwing the honeybadger error, does not.  It is invoked from `Hyrax::Actors::FileActor` via `.send`.  It might be `:perform_now` or `:perform_later`.  Perhaps it should use `Hyrax::WorkingDirectory` like the other jobs?  Because when it is `:perform_later`, as above, it might end up executing on a different box, different filesystem.

**Comment by mjgiarlo** [comment]
@atz That is eminently reasonable. Thanks for taking this on!

**Comment by atz** [comment]
`FileActor` tries to prep for the `IngestFileJob` by calling 
```ruby
Hyrax::WorkingDirectory.copy_file_to_working_directory(file, file_set.id)
```

But that doesn't make any sense when it calls `perform_later` and that (maybe) gets serviced on a separate box anyway. 

`Hyrax::WorkingDirectory` has its own problems, namely expecting to be able to call `StringIO.new(file.content)`.  `file` is an `ActiveFedora::File`, so afaict, that means it expects to hold the entire file in memory at once, just to initialize a `StringIO` object with it.  

We have two architectural problems: 
- decomposition of these jobs meaning that each one potentially has to refetch a remote file resource.  
- our fetching of remote file resource, even where we do it, is treating media files as strings it can hold in memory.
- also, `ActiveFedora::File.find('id')` always returns an object, effectively is `new(:id => id)` where no File exists.  That's completely anti-pattern.

**Comment by atz** [comment]
IMO, each job should default to retrieving (from some util class like WorkingDirectory) an IO for the file.  Doesn’t matter where it was from.  They should *not* default to expecting a filesystem file.

IF a literal local file is required (because we are handing off to some java process or something, ugh…), the job should use a separate code path to do it.

`WorkingDirectory` is built around filepaths and filesystem copying, so that is problematic.  That assumption goes all the way down to `Hydra::Derivatives::Processors`:
https://github.com/samvera/hydra-derivatives/blob/master/lib/hydra/derivatives/processors/processor.rb#L6-L13

That is unworkable for sufficiently large files, e.g. video.  It sorta amazes me that we have a single `Hyrax::FileSetDerivativesService` that hardcodes all serviced filetypes and hardcodes their mapping to derivatives, including audio/video file formats, thumbnail sizes, etc.  Nothing of it is configurable.  Everything runs on filename, including:
- `Hydra::Derivatives::PdfDerivatives`
- `Hydra::Derivatives::FullTextExtract`
- `Hydra::Derivatives::DocumentDerivatives`
- `Hydra::Derivatives::AudioDerivatives`
- `Hydra::Derivatives::VideoDerivatives`
- `Hydra::Derivatives::ImageDerivatives`

I guess I was unaware that most of the derivative processors are non-ruby that we shell out to.  But I cannot believe *all* of them fundamentally cannot use IO/STDIN instead of a filepath.

**Comment by atz** [comment]
`ffmpeg`, for example, supports `pipe` input and output, for the formats we care about: https://stackoverflow.com/questions/12999674/ffmpeg-which-file-formats-support-stdin-usage

**Comment by atz** [comment]
This is a non-literal "summary" trace of what happens on uploading the replacement file:
```ruby
# HTTP POST (patch) 
action="/concern/file_sets/dd52ac5d-26af-4254-939f-e3603686528c?locale=en"

# app/controllers/concerns/hyrax/file_sets_controller_behavior.rb in #attempt_update()
Hyrax::Actors::FileSetActor.new(@file_set, current_user).update_content(params[:file_set][:files].first)

# app/actors/hyrax/actors/file_set_actor.rb in #update_content
Hyrax::Actors::FileActor.new(file_set, 'original_file', user).ingest_file(file, true)

# app/actors/hyrax/actors/file_actor.rb in #ingest_file
IngestFileJob.perform_later(
                             file_set,
                             working_file(file),
                             user,
                             ingest_options(file)
                           )

# ... in #working_file
Hyrax::WorkingDirectory.copy_file_to_working_directory(file, file_set.id)

# app/services/hyrax/working_directory.rb
def copy_file_to_working_directory(file, id)
  file_name = file.respond_to?(:original_filename) ? file.original_filename : ::File.basename(file)
  copy_stream_to_working_directory(id, file_name, file)
end

def copy_stream_to_working_directory(id, name, stream)
  working_path = full_filename(id, name)
  Rails.logger.debug "Writing #{name} to the working directory at #{working_path}"
  FileUtils.mkdir_p(File.dirname(working_path))
  IO.copy_stream(stream, working_path)
  working_path
end
```

**Comment by atz** [comment]
The basic problem is that each time a job is called, the context shifts and the parameters you can pass the job are constrained:
- different filesystem (/tmp is different!)
- different execution time (/tmp might have been cleaned out since the job was queued!)
- params are serialized with **upper limit on size**: basic objects are ok, but binaries are too big!  filehandles are impossible.

Here we are passing the filepath because we cannot pass the filehandle, and because this is all early in the ingest pipe, we haven't put the file in fedora yet, so we cannot even pass the ID and then fetch on the inside of the job.  Effectively, the path is the only ID we have for it, but it is useless for our purposes: it cannot be used on a worker box to fetch the file unless it magically happens to exist on filesystem.

For a basic Hyrax, everything might run on the same box, and it will appear to "work".  But for Hyku, the job worker is guaranteed to be a different box and the uploaded file lives on S3 immediately.  We need an abstraction layer in Hyrax that allows us out of the trap of using the path as the ID.  The obvious choice is just to use the `Hyrax::UploadFile` model.

**Comment by atz** [comment]
Blocked by: https://github.com/samvera/hyrax/issues/1155

Working on that.

**Comment by mjgiarlo** [comment]
@atz Think we can close this one now, too?
