### ISSUE TITLE
reconsider placement of Representative Media and Thumbnail selection on work edit screen

### ISSUE THREAD

**Issue by hannahfrost** [samvera-labs/hyku#1188]
Currently these selections appear under the "Additional fields" label. This is not an ideal location as it is incongruous with the descriptive metadata form.

Perhaps these selections belong on the Files tab?

**Comment by jcoyne** [comment]
I'm not sure that it is incongruous.  "Here is a thumbnail which describes the work visually"  "Here is a file which represents the work as a whole" Do these not describe?

**Comment by jcoyne** [comment]
Task says "reconsider".  I have reconsidered.  Okay to close 😉

**Comment by hannahfrost** [comment]
@jcoyne Thanks for considering! :)

I personally don't like the current approach -- the current implementation needs a little sprucing up at least and I feel that addressing these selections in the middle of a metadata form is inappropriate. 

I would like @ggeisler to weigh in when he has a moment.

**Comment by ggeisler** [comment]
I agree with @hannahfrost. Technically, @jcoyne might be correct that these choices could be considered a "description" of the work, but I'd bet that most users (who might know that there is some way to add a thumbnail for a work because they've seen it for other works) would not use the logic that a thumbnail is a way to describe a work and thus the option should be somewhere under the "Descriptions" tab. I'd guess it is much more likely the user's logic would be, _I want to make one of the files represent the work, so I'll go look at the Files tab_.

I think this would be true even if these choices weren't hidden behind the "Additional fields" toggle; that just makes them even harder to find.

Below is a potential reorganization that moves the options to the Files tab (in this mockup I also added column headers to the files table; I assume there should be an image preview image or icon at the left side of the table so that's why there's some extra space in the first column).

An additional advantage of this approach is that (if I understand correctly) these two choices don't appear in the UI until files are added. With the current approach, the user would have to know that after adding files, she should return to the Descriptions tab and expand the "Additional fields" toggle to associate file(s) with the options. With the options relocated to the Files tab, it seems much more likely that the user will see them, since they will appear on the same tab used to upload the files required for the options to be displayed, and can be used as soon as the files are successfully uploaded.

![new_work____institution_digital_repository](https://cloud.githubusercontent.com/assets/101482/26807824/a2b0498c-4a0d-11e7-80f3-a387c221198d.png)

**Comment by hannahfrost** [comment]
@ggeisler  This is exactly what I had in mind. Thanks for whipping up the mockup.

**Comment by mjgiarlo** [comment]
Dig it! @hannahfrost priority?

**Comment by hannahfrost** [comment]
@jcoyne and I just talked about this. Next step is to turn this into two tickets: one for moving the selection to the Files tab; another for making the file selection appear as soon as there are files uploaded. Should these be in Hyrax?

Priority is relatively low, given the number of other competing priorities.

**Comment by mjgiarlo** [comment]
@hannahfrost Yep, Hyrax issues. Thanks!

**Comment by hannahfrost** [comment]
Decomposed into https://github.com/samvera-labs/hyrax/issues/1147 and https://github.com/samvera-labs/hyrax/issues/1148
