### ISSUE TITLE
Share tab not appearing on work creation screens as expected

### ISSUE THREAD

**Issue by hannahfrost** [samvera-labs/hyku#1195]
I do believe we only need it to show once.

**Comment by hannahfrost** [comment]
Already noted in https://github.com/samvera-labs/hyrax/issues/976

**Comment by hannahfrost** [comment]
Correcting this ticket which was mischaracterized originally.

The Share tab appears a second time on the Add News Works by Batch screen only when the Default Admin Set is assigned to the batch of works. If I pick a different Admin Set, just one Share tab.

When creating a single work, there is no Share tab until the Default Admin Set is assigned to the work. If I pick another Admin Set, so Share tab.

I would expect the Share tab to appear in all work creation scenarios, regardless of Admin Set selection.

**Comment by jcoyne** [comment]
> I would expect the Share tab to appear in all work creation scenarios, regardless of, and independent of, Admin Set selection.

The share tab is dependent on whether or not a mediated deposit workflow is active for the selected admin set.  We don't want the creator to share edit access to something going through mediated deposit.

**Comment by ggeisler** [comment]
Would it make more sense to always show the Share tab and just adjust the content of the tab to reflect whether or not the current user can currently do any sharing of the work?

In other words, if the work is in the process of mediated deposit and thus not currently eligible for sharing, show the Share tab but on the tabbed page show a flash message (e.g., "This work is under review and cannot be shared until the review process is completed.") instead of the sharing controls.

I might be missing something about the whole issue but generally speaking having a tab that only shows up under certain circumstances is bound to cause confusion among users, some of whom might not even know things can undergo review, etc.

**Comment by jcoyne** [comment]
@ggeisler I would imagine that some users would only have the ability to deposit into mediated admin sets, so the presence of a tab with no/inactive content would just be clutter to them.

**Comment by ggeisler** [comment]
@jcoyne I don't think I understand. If I deposit a work into a mediated admin set, when that work is eventually approved, wouldn't I then be able to share it?

**Comment by jcoyne** [comment]
@ggeisler the share tab allows granting edit access to other users.  We may have been a little heavy handed in turning off all sharing instead of just edit sharing.

**Comment by jcoyne** [comment]
@hannahfrost is going to open a new ticket about the design of the share tab.
