### ISSUE TITLE
When changing banner image, allow for updating the attribution

### ISSUE THREAD

**Issue by geekscruff** [samvera-labs/hyku#1217]
### Descriptive summary

If you change the banner image, the attribution in the footer is rendered incorrect. I suggest making it easier to edit the attribution, ideally at the same time as updating the banner image.

### Expected behavior

Update attribution with banner image.

### Actual behavior

Attribution stays the same and so is wrong when the banner gets updated.

### Steps to reproduce the behavior

1. Replace the banner image in the admin panel
2. Look at the attribution

**Comment by ggeisler** [comment]
@mjgiarlo Do you have a sense of how likely it is that implementors will actually want to use an image that requires attribution? I'm wondering if this just feels like an issue because Hyrax/Hyku happens to ship with a default image that does require attribution, and in reality anyone really using the application for their organization is very likely to use an image associated with their organization and thus not likely to need attribution (e.g., Stanford's version of Hyku could use any number of Stanford-related imagery and not have to provide explicit attribution).

If the above is more or less true, it seems like we could just 1) ship with an image that doesn't require attribution and 2) let the rare implementor who needs to add attribution for an image they add to deal with it themselves by customizing the footer (or wherever they want to handle it).

I guess I'm just suggesting that it feels to me that building in a way to enable an implementor to easily add a banner image attribution seems like a lot of work for something than in practice might almost never be needed. But maybe I'm underestimating how often implementors will use images in the banner that require attribution?

**Comment by mjgiarlo** [comment]
@ggeisler I don't have a sense of this, no. I suspect you are right, though, that we may not need this feature (until told explicitly that we do). So in that vein... I'm tagging @samvera-labs/hyrax-code-reviewers and @samvera-labs/hyrax-ui-ux-advisors to get a broader set of folks to chime in.

**Comment by newmanld** [comment]
I can confirm that at Cincinnati we are currently using an image that does require attribution.  Doesn't mean that we wouldn't customize the footer anyway or customize the attribution statement somewhere else.

**Comment by ggeisler** [comment]
@mjgiarlo Just noting that as an example (one I assume you know about!), Scholar Sphere does provide an attribution for their custom banner image, but does so in a way that I don't think would work well with a generic slot for attribution in the site footer. So (and I don't mean this to preclude other input) this seems like an example where the implementor does want to include attribution but would still use a custom solution rather than anything we provided in the app (I assume, given the lengthy attribution in that example).

**Comment by jcoyne** [comment]
Instead of "customize the attribution" how about "customize the footer text"?

**Comment by ggeisler** [comment]
https://github.com/samvera-labs/hyrax/issues/189

**Comment by mjgiarlo** [comment]
@geekscruff @newmanld As @jcoyne and @ggeisler have mentioned, might https://github.com/samvera-labs/hyrax/issues/189 replace this ticket?

**Comment by geekscruff** [comment]
Yes, that's much better!

**Comment by mjgiarlo** [comment]
@geekscruff OK! Shall we close this issue? (Have at it!)

**Comment by geekscruff** [comment]
Closing :point_up:

**Comment by mjgiarlo** [comment]
Thanks!
