### ISSUE TITLE
Cleanup account job to ignore NilSolrEndpoint error

### ISSUE THREAD

**Issue by bbranan** [samvera-labs/hyku#1351]
Background:

When attempting to create a tenant last week, Heather ran into an error where Solr was unavailable because it could not talk to Zookeeper. (https://app.honeybadger.io/projects/48327/faults/34032248). The Solr connection issues have been cleared up, but now we're in a state where the app thinks a tenant exists, but no solr index for that tenant was ever created. Attempting to delete the tenant (from the UI) results in https://app.honeybadger.io/projects/48327/faults/34103318.

Justin's analysis:

cleanup_account_job should be changed to ignore NilSolrEndpoint

this line: https://github.com/samvera-labs/hyku/blob/master/app/jobs/cleanup_account_job.rb#L40

**Comment by atz** [comment]
`NilSolrEndpoint` should not exist.  If we cannot `switch!` all endpoints successfully, then we cannot fulfill the expectations established by `Apartment`.  

It is (or at least was and *should be*) unacceptable for `switch!` to leave the application in a state where it can, for example, write to Fedora OK but then bomb updating solr, because then the state is out of sync and unrecoverable.  Given that `ActiveFedora` has already sacrificed transactionality, there is not even the possibility of rolling back the Fedora writes.

**Comment by bbranan** [comment]
@atz The goal of this issue is to allow for removing a tenant which failed to complete the account creation process. Are you suggesting that rather than making the change to ignore NilSolrEndpoint when doing that cleanup (or perhaps in addition to that change) the action to create an account in the first place should be wrapped in a transaction such that this scenario would never present itself?

My (limited) understanding of hyku/hyrax leads me to believe that in order to ensure consistency across the board like you suggest would mean implementing transactions around all actions which touch multiple data stores. If I have that right, it would seem to be a change of a much larger scope that would warrant a stand-alone ticket.
