### ISSUE TITLE
Depositing work into collection is not intuitive

### ISSUE THREAD

**Issue by bbranan** [samvera-labs/hyku#1374]
More than one of the HykuDirect pilot users were confused by the fact that if you select a collection, click on "Add works", then "Add new work", then upload a file, your work will not be added to the collection unless you also go to the Relationships tab (while creating the work) and select the collection.

As a depositor, I should be able to select a collection, then deposit works into that collection without needing to indicate again that really I want this work in this collection.

**Comment by hannahfrost** [comment]
@bbranan Does this design by @ggeisler seem like it will address the issue you reported?
https://github.com/samvera/hyrax/issues/1370

**Comment by bbranan** [comment]
@hannahfrost Not really. The linked design allows for adding existing works to a collection. This issue is about how to create a new work in a collection. The analog to this on a file system would be selecting a directory and creating a new file in that directory. The design @ggeisler created is more similar to moving existing files into a directory. Both paths for organizing works in collections are needed.

**Comment by ggeisler** [comment]
Right, I agree with @bbranan. The problem he's reporting here doesn't seem to be a UI issue; the problem is that the collection the user started the add work process from is not being remembered or applied when the user gets to the Add Work page. The code should be keeping track of what collection the user started from and use that info to update the associated collection aspect of the Relationships tab of the work being created.

**Comment by mjgiarlo** [comment]
Began work on this here: https://github.com/samvera/hyrax/pull/1453
