### ISSUE TITLE
Remove Lease visibility

### ISSUE THREAD

**Issue by jcoyne** [samvera-labs/hyku#423]

**Comment by atz** [comment]
Can you provide some details?  You mean suppress the display of lease terms?

**Comment by jcoyne** [comment]
Lease is something that is in hyrax, but is not in Gary's designs.  So, one way we could do this would be to add the Lease stuff to a flipflop switch in Hyrax and have it turned off in hyku.

**Comment by ggeisler** [comment]
Just to be clear, it isn't in the designs because @hannahfrost and I didn't see anything in the HyBox user research that justified keeping it (and the UI complexity that it adds).

**Comment by ggeisler** [comment]
@jcoyne By "have it turned off in hyku" do you mean show the flipflop switch but set it to off, or disabled, or just not surfaced in Hyku?

Your suggestion sounds fine to me, but I just want to make sure you aren't suggesting that the Hyku user would have the ability to turn the Lease flipflop switch back on. I think that would be problem, since the Release and Visibility page of the Admin Set configuration doesn't provide a way to configure lease details.

**Comment by mjgiarlo** [comment]
@hannahfrost Do you see this as MVP work or post-MVP?

**Comment by hannahfrost** [comment]
@mjgiarlo Post-MVP. I like idea by @jcoyne to make it a flippable feature.

**Comment by ggeisler** [comment]
@hannahfrost Flippable in Hyku so they have the option to make the lease option visible in Hyku?

**Comment by hannahfrost** [comment]
@ggeisler No, I don't think so (sorry I left that comment open for misinterpretation). I don't think we need lease in Hyku at all. If it is flippable in the underlying code base, and ships in Hyku as flipped off, can we live with that? Do we need to accommodate it in the design in the event someone flips it on?

In any case, post MVP.

**Comment by ggeisler** [comment]
@hannahfrost Yes, I believe that even if we ship it Hyku in the off state, if the switch is enabled there is design work to do (see my comment above directed at @jcoyne).

I'm not taking a stand on whether we should or shouldn't do it, just pointing out that I think allowing leases in Hyku has implications beyond just showing the lease option in the Edit Work sidebar. (But if someone else sees it otherwise feel free to correct me.)
