### ISSUE TITLE
add standard thesauri to dc:resource_type element for Image Work

### ISSUE THREAD

**Issue by hannahfrost** [samvera-labs/hyku#879]
Currently Hyku offers a local vocabulary to assign a resource type to dc:resource_type

With the introduction of the Image Work type (and other specific content types to come), we should offer the option to apply authorized terms with URIs from standard vocabularies like AAT and TGM in a repeated instance of the resource_type element.

**Comment by ruthtillman** [comment]
This is a quick heading to lunch tag but is this something @projecthydra-labs/hyrax-metadataists might want to talk about?

**Comment by remerjohnson** [comment]
I'm a bit distant , but are we talking about `dc:type` and the loosely equivalent `mods:type_of_resource`? If so, I think our approach will be to use [LoC ResourceType URIs](http://id.loc.gov/vocabulary/resourceTypes.html).  

We did definitely consider Getty Vocab for this, but would be interested to see how others would tackle that.

**Comment by ruthtillman** [comment]
Got clarification on the slack this is for dc:type. And currently the local vocab could be https://github.com/projecthydra-labs/hyrax/blob/master/lib/generators/hyrax/templates/config/authorities/resource_types.yml but then if I'm understanding the issue correctly, it would be the ability to pull in a dc:type of resource (so high-level work type) that comes from different standardized vocabs? I tagged folks in hopes of exactly the kind of thing you brought in @remerjohnson, seeing what people are either using or planning to use so those vocabs might be available? (trying to be aware of metadata stuff getting worked on)

**Comment by mjgiarlo** [comment]
## Questions to answer before this issue is actionable

1. Which vocabulary, or vocabularies, do we want to support for resource types?
2. Is there a requirement that the terms come from a remote endpoint or may they be served locally (like the current implementation)?
3. Do we need to provide a data migration for folks upgrading to Hyrax 2.x (acknowledging that they may have extended Hyrax's built-in resource types)?
  1. Do we continue to allow strings in this field, or do we now require URIs?

**Comment by mjgiarlo** [comment]
@hannahfrost @cmh2166 advice on the above? :point_up:

**Comment by cmh2166** [comment]
Presumptions: 
- [:resource_type maps to dcterms:type, which has range non-literal value but is used with literal](https://github.com/projecthydra-labs/hyrax/blob/master/app/models/concerns/hyrax/basic_metadata.rb#L16)
- [current resource_type terms in hyrax aren't DCMI types but closer to form/genres combo](https://github.com/projecthydra-labs/hyrax/blob/master/lib/generators/hyrax/templates/config/authorities/resource_types.yml)

Preferred approach to resource_type (this aligns too with DPLA MAP v.4 and DCMI recommendations for dcterms:type / dc:type):
- change `dcterms:type`/resource_type to capture [DCMI Type URIs](http://dublincore.org/documents/dcmi-terms/#dcmitype-Collection) or [LC Resource Types](http://id.loc.gov/vocabulary/resourceTypes.html). Less involved alternative: use `dc:type` (dc elements) instead with DCMI Type labels captured as literals.
- add `edm:hasType`/genre (edm=Europeana Data Model) to capture the more genre/form-like terms currently in current resource_type terms. `edm:hasType` would take URIs from [LC Form/Genre Terms](http://id.loc.gov/authorities/genreForms.html), [AAT](http://vocab.getty.edu/), [LC TGM](http://id.loc.gov/vocabulary/graphicMaterials.html), ... (these 3 should be a good place for metadataists to start in their implementation profile decisions).

Actually answering @mjgiarlo's questions:
1. split resource types into `resource_type` & `genre` to make this easier to answer/understand. resource_type would pull from [DCMI Types](http://dublincore.org/documents/dcmi-terms/#dcmitype-Collection) and [LC Resource Types](http://id.loc.gov/vocabulary/resourceTypes.html). `resource_type` could take URIs or literals depending on what's easier to implement now. `genre` would pull from [AAT](http://vocab.getty.edu/), [LC Form/Genre Terms](http://id.loc.gov/authorities/genreForms.html), [LC TGM](http://id.loc.gov/vocabulary/graphicMaterials.html) and take URIs.
2. remote endpoint here means querying the externally managed data instead of some intermediate lookup cache or forked dataset? for resource_type: no need to externally manage, those type terms are really stable, few in number, and could be added locally. for genre: probably an incentive to retrieve from external sources (or forks of external sources) in order to build in ability to later develop extended usage of those knowledge graphs.
3. yes. happy to provide mappings, docs, whatever for both.
4. types: could go either way; genres: no if at all possible to implement now.

**Comment by mjgiarlo** [comment]
@hannahfrost When you get a minute, can you review what @cmh2166 wrote above? Let's come up with a plan of action, including what all we should include in scope for this issue (and what we can/should punt for after OR2017).

**Comment by hannahfrost** [comment]
Catching up with you, @mjgiarlo and @cmh2166. The split approach for `resource_type` and `genre` is very appealing (and aligns with Stanford's practices). I think the first course of action should be to keep `resource_type` as local literals and to implement externally-provided and managed vocabs and URIs for `genre`. I don't see an argument for starting an implementation of `genre` anywhere but in this way. 

If we have consensus on this approach, and agree that it sets us up for a strong, generalizable pattern for future work types, I suggest that this new functionality should be prioritized after the current spate of bug fixes leading up to OR. Also if taking some time to vet the approach more broadly is likely to lead good effect (eg., for Hyrax users generally), then let's take a bit of time to do that.

**Comment by cmh2166** [comment]
Just to clarify, that first step would also involve some terms currently used in resource_type field to shift to a new genre field (i.e. 'Book', 'Capstone Project', both of which would then have type 'Text')- or we just setting up the fields first then migrating values as a second step?

**Comment by geekscruff** [comment]
Could resource types be done in the same way as location is now handled, ie. where both URI and label are stored? That way we can have a local authority, but one that has formal URIs and Labels.

Genre could be added as a property now, and then could hoover up any literals no longer in resource type. Then a later stage could be to support the external vocabs?

**Comment by geekscruff** [comment]
Gists for dc and loc resource types:

LOC: https://gist.github.com/geekscruff/1a770872b39a98fad1ec8556d2582450
DC: https://gist.github.com/geekscruff/2780fac92a4ac92710c54e1d3a452ea1

**Comment by cmh2166** [comment]
@geekscruff sure, i think we're saying the same thing.

**Comment by geekscruff** [comment]
Always good to be in agreement. Gists were intended to help with file-based deployment if that's the plan. If not, no biggie.

**Comment by cmh2166** [comment]
rad, thanks @geekscruff

**Comment by remerjohnson** [comment]
I _think_ this vaguely aligns with UCSD's plan for this last year, as we were planning to have `genre` treated similarly to our subjects/topics/people, pointing to external URIs from Getty/FormGenre/etc. terms. :+1: 

What we didn't resolve was how/if we'd want to control the total amount of terms to address discoverability. That is, we were concerned that if we had tons of granular genre terms, it might be difficult for a user to be able to just find e.g. all our aerial photographs, unless they had already stumbled across one. But that is a discussion for another day.

**Comment by cmh2166** [comment]
breaking into multiple tickets for steps moving work forward.

**Comment by cmh2166** [comment]
Thanks @remerjohnson for your input. I think the selection of a subset of terms for genre (or selection of what vocabs/sources you want for genre generally) becomes an implementation question.

**Comment by mjgiarlo** [comment]
Now that this ticket has been decomposed, I'm marking this as an epic and closing it. Thanks for the discussion, all!
